### ISSUE TITLE
composer.lock should be committed

### ISSUE THREAD

**Issue by rodrigopedra** [Lakshan-Madushanka/movieshark#18]
First of all, nice project!

As this is a project, and not a library, `composer.lock` should be committed, such as `package-lock.json` is already committed, so dependencies are frozen in time, and installing always brings the app to the same state.

For example, Inertia.js's demo app has its `composer.lock` file available in their repo:

https://github.com/inertiajs/pingcrm/blob/0a798fadc87dc1cf22933bb1224c834df53579f5/composer.lock

**Comment by Lakshan-Madushanka** [comment]
@rodrigopedra Thanks. Added `composer.lock`. I didn't intentionally omit it, but somehow it was missed in a commit.
